version: '3.9'

services:
  # ==========================
  # Backend Laravel (PHP-FPM)
  # ==========================
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_api
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    expose:
      - "9000"
    networks:
      - laravel_net

  # ==========================
  # Nginx com builds Angular
  # ==========================
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_web
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
